/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractsSol from "./Contracts.sol";
export type { contractsSol };
import type * as contracts2Sol from "./Contracts2.sol";
export type { contracts2Sol };
