/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as contractsSol from "./Contracts.sol";
export * as contracts2Sol from "./Contracts2.sol";
export * as anotherContracts from "./another-contracts";
