/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ContractWithExternalLibraryContract extends Truffle.Contract<ContractWithExternalLibraryInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ContractWithExternalLibraryInstance>;
}

type AllEvents = never;

export interface ContractWithExternalLibraryInstance extends Truffle.ContractInstance {
  lib(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  lib2(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  lib3(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  lib4(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    lib(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    lib2(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    lib3(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    lib4(txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void,
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(event: string, callback: (error: Error, event: EventData) => void): Promise<EventData[]>;
}
