/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ContractWithExternalLibraryInterface extends Interface {
  getFunction(nameOrSignature: "lib" | "lib2"): FunctionFragment;

  encodeFunctionData(functionFragment: "lib", values?: undefined): string;
  encodeFunctionData(functionFragment: "lib2", values?: undefined): string;

  decodeFunctionResult(functionFragment: "lib", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lib2", data: BytesLike): Result;
}

export interface ContractWithExternalLibrary extends BaseContract {
  connect(runner?: ContractRunner | null): ContractWithExternalLibrary;
  waitForDeployment(): Promise<this>;

  interface: ContractWithExternalLibraryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  lib: TypedContractMethod<[], [bigint], "nonpayable">;

  lib2: TypedContractMethod<[], [bigint], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "lib"): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(nameOrSignature: "lib2"): TypedContractMethod<[], [bigint], "nonpayable">;

  filters: {};
}
